project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "chapters/*.qmd"
    - "!README.md"
    - "!appendix-document-metadata.qmd"
    - "!references.qmd"

website:
  title: "Quarto Website Template"
  site-url: https://ucd-serg.github.io/qwt/
  description: "A template for creating websites with Quarto"
  page-footer:
    center: "Built with [Quarto](https://quarto.org/)"
  back-to-top-navigation: true
  page-navigation: true
  reader-mode: true
  repo-url: https://github.com/UCD-SERG/qwt
  repo-actions: [edit, issue, source]
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Chapters"
        menu:
          - text: "Chapter 1: Introduction"
            href: chapters/chapter1.qmd
          - text: "Chapter 2: Advanced Topics"
            href: chapters/chapter2.qmd
    right:
      - icon: github
        href: https://github.com/UCD-SERG/qwt
        aria-label: GitHub

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    toc: true
    anchor-sections: true
    toc-location: right
    toc-depth: 3
    code-fold: false
    code-tools: true
    code-link: true
    highlight-style: pygments
    lightbox: true
    link-external-icon: true
    embed-resources: false
    fig-cap-location: top
    html-math-method: mathjax
    number-sections: true
    number-depth: 3
    df-print: paged
  docx:
    number-sections: true
    number-depth: 3
    df-print: tibble
    prefer-html: true
  revealjs:
    output-file: "{stem}-slides.html"
    theme: simple
    slide-number: true
    chalkboard: false
    preview-links: auto
    controls: true
    transition: slide
    background-transition: fade
    lightbox: true
    fig-cap-location: top
    html-math-method: mathjax
    smaller: true
    number-sections: true
    progress: true
    incremental: false
    df-print: paged
    number-depth: 2
    shift-heading-level-by: 0
    slide-level: 2
    scrollable: true
    echo: true
    margin: 0.0
    code-fold: true
    code-link: true
    code-summary: "[R code]"
    auto-stretch: true
    fig-height: 5
    fig-width: 7

execute:
  warning: false
  message: false
  cache: false
  freeze: auto

knitr:
  opts_chunk:
    collapse: true
    comment: "#>"
